version: "3.2"

services:
  judger:
    image: ahpuoj_judger:1.0.0
    container_name: ahpuojv2_judger
    tty: true
    depends_on:
      - db
    volumes:
      - ${OJ_DATA_PATH_HOST}:${OJ_DATA_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
    links:
      - db
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    privileged: true
  db:
    image: mysql:latest
    container_name: ahpuojv2_mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai

  redis:
    image: redis:latest
    container_name: ahpuojv2_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
