version: "3.2"

services:
  judger:
    image: ahpuoj_judger:1.0.0
    container_name: ahpuojv2_judger
    tty: true
    volumes:
      - ${OJ_DATA_PATH_HOST}:${OJ_DATA_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
    depends_on:
      - db
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    privileged: true
  db:
    image: mysql:latest
    container_name: ahpuojv2_mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai

  redis:
    image: redis:latest
    container_name: ahpuojv2_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: ahpuoj_nginx
    restart: always
    ports:
      - 80:80
    #   - 443:443
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${OJ_WEB_PATH_HOST}:${OJ_WEB_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
